// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/connector.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensajes del Connector al Gateway
type ConnectorMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConnectorMessage_Register
	//	*ConnectorMessage_FlightInfo
	//	*ConnectorMessage_ArrowChunk
	//	*ConnectorMessage_StreamStatus
	//	*ConnectorMessage_Heartbeat
	Payload       isConnectorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorMessage) Reset() {
	*x = ConnectorMessage{}
	mi := &file_proto_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorMessage) ProtoMessage() {}

func (x *ConnectorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorMessage.ProtoReflect.Descriptor instead.
func (*ConnectorMessage) Descriptor() ([]byte, []int) {
	return file_proto_connector_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectorMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConnectorMessage) GetPayload() isConnectorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConnectorMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*ConnectorMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ConnectorMessage) GetFlightInfo() *FlightInfoResponse {
	if x != nil {
		if x, ok := x.Payload.(*ConnectorMessage_FlightInfo); ok {
			return x.FlightInfo
		}
	}
	return nil
}

func (x *ConnectorMessage) GetArrowChunk() *ArrowChunk {
	if x != nil {
		if x, ok := x.Payload.(*ConnectorMessage_ArrowChunk); ok {
			return x.ArrowChunk
		}
	}
	return nil
}

func (x *ConnectorMessage) GetStreamStatus() *StreamStatus {
	if x != nil {
		if x, ok := x.Payload.(*ConnectorMessage_StreamStatus); ok {
			return x.StreamStatus
		}
	}
	return nil
}

func (x *ConnectorMessage) GetHeartbeat() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Payload.(*ConnectorMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isConnectorMessage_Payload interface {
	isConnectorMessage_Payload()
}

type ConnectorMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type ConnectorMessage_FlightInfo struct {
	FlightInfo *FlightInfoResponse `protobuf:"bytes,3,opt,name=flight_info,json=flightInfo,proto3,oneof"`
}

type ConnectorMessage_ArrowChunk struct {
	ArrowChunk *ArrowChunk `protobuf:"bytes,4,opt,name=arrow_chunk,json=arrowChunk,proto3,oneof"`
}

type ConnectorMessage_StreamStatus struct {
	StreamStatus *StreamStatus `protobuf:"bytes,5,opt,name=stream_status,json=streamStatus,proto3,oneof"`
}

type ConnectorMessage_Heartbeat struct {
	Heartbeat *HeartbeatResponse `protobuf:"bytes,6,opt,name=heartbeat,proto3,oneof"`
}

func (*ConnectorMessage_Register) isConnectorMessage_Payload() {}

func (*ConnectorMessage_FlightInfo) isConnectorMessage_Payload() {}

func (*ConnectorMessage_ArrowChunk) isConnectorMessage_Payload() {}

func (*ConnectorMessage_StreamStatus) isConnectorMessage_Payload() {}

func (*ConnectorMessage_Heartbeat) isConnectorMessage_Payload() {}

// Comandos del Gateway al Connector
type GatewayCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*GatewayCommand_RegisterResponse
	//	*GatewayCommand_GetFlightInfo
	//	*GatewayCommand_DoGet
	//	*GatewayCommand_Heartbeat
	Command       isGatewayCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayCommand) Reset() {
	*x = GatewayCommand{}
	mi := &file_proto_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCommand) ProtoMessage() {}

func (x *GatewayCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCommand.ProtoReflect.Descriptor instead.
func (*GatewayCommand) Descriptor() ([]byte, []int) {
	return file_proto_connector_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GatewayCommand) GetCommand() isGatewayCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *GatewayCommand) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Command.(*GatewayCommand_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *GatewayCommand) GetGetFlightInfo() *GetFlightInfoRequest {
	if x != nil {
		if x, ok := x.Command.(*GatewayCommand_GetFlightInfo); ok {
			return x.GetFlightInfo
		}
	}
	return nil
}

func (x *GatewayCommand) GetDoGet() *DoGetRequest {
	if x != nil {
		if x, ok := x.Command.(*GatewayCommand_DoGet); ok {
			return x.DoGet
		}
	}
	return nil
}

func (x *GatewayCommand) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Command.(*GatewayCommand_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isGatewayCommand_Command interface {
	isGatewayCommand_Command()
}

type GatewayCommand_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,2,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type GatewayCommand_GetFlightInfo struct {
	GetFlightInfo *GetFlightInfoRequest `protobuf:"bytes,3,opt,name=get_flight_info,json=getFlightInfo,proto3,oneof"`
}

type GatewayCommand_DoGet struct {
	DoGet *DoGetRequest `protobuf:"bytes,4,opt,name=do_get,json=doGet,proto3,oneof"`
}

type GatewayCommand_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,5,opt,name=heartbeat,proto3,oneof"`
}

func (*GatewayCommand_RegisterResponse) isGatewayCommand_Command() {}

func (*GatewayCommand_GetFlightInfo) isGatewayCommand_Command() {}

func (*GatewayCommand_DoGet) isGatewayCommand_Command() {}

func (*GatewayCommand_Heartbeat) isGatewayCommand_Command() {}

// ============== Registro ==============
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Datasets      []string               `protobuf:"bytes,3,rep,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_connector_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetDatasets() []string {
	if x != nil {
		return x.Datasets
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_connector_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ============== Flight Info ==============
type GetFlightInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []string               `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	Rows          int64                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlightInfoRequest) Reset() {
	*x = GetFlightInfoRequest{}
	mi := &file_proto_connector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlightInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightInfoRequest) ProtoMessage() {}

func (x *GetFlightInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFlightInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_connector_proto_rawDescGZIP(), []int{4}
}

func (x *GetFlightInfoRequest) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *GetFlightInfoRequest) GetRows() int64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type FlightInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Schema        []byte                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"` // Arrow schema serializado
	TotalRecords  int64                  `protobuf:"varint,3,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Dataset       string                 `protobuf:"bytes,5,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Partitions    int32                  `protobuf:"varint,6,opt,name=partitions,proto3" json:"partitions,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightInfoResponse) Reset() {
	*x = FlightInfoResponse{}
	mi := &file_proto_connector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightInfoResponse) ProtoMessage() {}

func (x *FlightInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightInfoResponse.ProtoReflect.Descriptor instead.
func (*FlightInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_connector_proto_rawDescGZIP(), []int{5}
}

func (x *FlightInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FlightInfoResponse) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *FlightInfoResponse) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *FlightInfoResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *FlightInfoResponse) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *FlightInfoResponse) GetPartitions() int32 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

func (x *FlightInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ============== DoGet ==============
type DoGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        string                 `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"` // base64 encoded JSON con partition info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoGetRequest) Reset() {
	*x = DoGetRequest{}
	mi := &file_proto_connector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoGetRequest) ProtoMessage() {}

func (x *DoGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoGetRequest.ProtoReflect.Descriptor instead.
func (*DoGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_connector_proto_rawDescGZIP(), []int{6}
}

func (x *DoGetRequest) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

type ArrowChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Arrow IPC RecordBatch
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrowChunk) Reset() {
	*x = ArrowChunk{}
	mi := &file_proto_connector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowChunk) ProtoMessage() {}

func (x *ArrowChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowChunk.ProtoReflect.Descriptor instead.
func (*ArrowChunk) Descriptor() ([]byte, []int) {
	return file_proto_connector_proto_rawDescGZIP(), []int{7}
}

func (x *ArrowChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArrowChunk) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type StreamStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "stream_start" o "stream_end"
	Schema          []byte                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Partition       int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	TotalPartitions int32                  `protobuf:"varint,4,opt,name=total_partitions,json=totalPartitions,proto3" json:"total_partitions,omitempty"`
	TotalBytes      int64                  `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Error           string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamStatus) Reset() {
	*x = StreamStatus{}
	mi := &file_proto_connector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatus) ProtoMessage() {}

func (x *StreamStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatus.ProtoReflect.Descriptor instead.
func (*StreamStatus) Descriptor() ([]byte, []int) {
	return file_proto_connector_proto_rawDescGZIP(), []int{8}
}

func (x *StreamStatus) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StreamStatus) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *StreamStatus) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *StreamStatus) GetTotalPartitions() int32 {
	if x != nil {
		return x.TotalPartitions
	}
	return 0
}

func (x *StreamStatus) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StreamStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ============== Heartbeat ==============
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_connector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_connector_proto_rawDescGZIP(), []int{9}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_connector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_connector_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *HeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_connector_proto protoreflect.FileDescriptor

const file_proto_connector_proto_rawDesc = "" +
	"\n" +
	"\x15proto/connector.proto\x12\tconnector\"\xf0\x02\n" +
	"\x10ConnectorMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\bregister\x18\x02 \x01(\v2\x1a.connector.RegisterRequestH\x00R\bregister\x12@\n" +
	"\vflight_info\x18\x03 \x01(\v2\x1d.connector.FlightInfoResponseH\x00R\n" +
	"flightInfo\x128\n" +
	"\varrow_chunk\x18\x04 \x01(\v2\x15.connector.ArrowChunkH\x00R\n" +
	"arrowChunk\x12>\n" +
	"\rstream_status\x18\x05 \x01(\v2\x17.connector.StreamStatusH\x00R\fstreamStatus\x12<\n" +
	"\theartbeat\x18\x06 \x01(\v2\x1c.connector.HeartbeatResponseH\x00R\theartbeatB\t\n" +
	"\apayload\"\xb9\x02\n" +
	"\x0eGatewayCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12J\n" +
	"\x11register_response\x18\x02 \x01(\v2\x1b.connector.RegisterResponseH\x00R\x10registerResponse\x12I\n" +
	"\x0fget_flight_info\x18\x03 \x01(\v2\x1f.connector.GetFlightInfoRequestH\x00R\rgetFlightInfo\x120\n" +
	"\x06do_get\x18\x04 \x01(\v2\x17.connector.DoGetRequestH\x00R\x05doGet\x124\n" +
	"\theartbeat\x18\x05 \x01(\v2\x14.connector.HeartbeatH\x00R\theartbeatB\t\n" +
	"\acommand\"d\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bdatasets\x18\x03 \x03(\tR\bdatasets\"_\n" +
	"\x10RegisterResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\">\n" +
	"\x14GetFlightInfoRequest\x12\x12\n" +
	"\x04path\x18\x01 \x03(\tR\x04path\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x03R\x04rows\"\xda\x01\n" +
	"\x12FlightInfoResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\fR\x06schema\x12#\n" +
	"\rtotal_records\x18\x03 \x01(\x03R\ftotalRecords\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\x12\x18\n" +
	"\adataset\x18\x05 \x01(\tR\adataset\x12\x1e\n" +
	"\n" +
	"partitions\x18\x06 \x01(\x05R\n" +
	"partitions\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"&\n" +
	"\fDoGetRequest\x12\x16\n" +
	"\x06ticket\x18\x01 \x01(\tR\x06ticket\">\n" +
	"\n" +
	"ArrowChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\"\xba\x01\n" +
	"\fStreamStatus\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\fR\x06schema\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x12)\n" +
	"\x10total_partitions\x18\x04 \x01(\x05R\x0ftotalPartitions\x12\x1f\n" +
	"\vtotal_bytes\x18\x05 \x01(\x03R\n" +
	"totalBytes\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"N\n" +
	"\x11HeartbeatResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2[\n" +
	"\x10ConnectorService\x12G\n" +
	"\aConnect\x12\x1b.connector.ConnectorMessage\x1a\x19.connector.GatewayCommand\"\x00(\x010\x01B'Z%github.com/enrutador-gateway-go/protob\x06proto3"

var (
	file_proto_connector_proto_rawDescOnce sync.Once
	file_proto_connector_proto_rawDescData []byte
)

func file_proto_connector_proto_rawDescGZIP() []byte {
	file_proto_connector_proto_rawDescOnce.Do(func() {
		file_proto_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_connector_proto_rawDesc), len(file_proto_connector_proto_rawDesc)))
	})
	return file_proto_connector_proto_rawDescData
}

var file_proto_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_connector_proto_goTypes = []any{
	(*ConnectorMessage)(nil),     // 0: connector.ConnectorMessage
	(*GatewayCommand)(nil),       // 1: connector.GatewayCommand
	(*RegisterRequest)(nil),      // 2: connector.RegisterRequest
	(*RegisterResponse)(nil),     // 3: connector.RegisterResponse
	(*GetFlightInfoRequest)(nil), // 4: connector.GetFlightInfoRequest
	(*FlightInfoResponse)(nil),   // 5: connector.FlightInfoResponse
	(*DoGetRequest)(nil),         // 6: connector.DoGetRequest
	(*ArrowChunk)(nil),           // 7: connector.ArrowChunk
	(*StreamStatus)(nil),         // 8: connector.StreamStatus
	(*Heartbeat)(nil),            // 9: connector.Heartbeat
	(*HeartbeatResponse)(nil),    // 10: connector.HeartbeatResponse
}
var file_proto_connector_proto_depIdxs = []int32{
	2,  // 0: connector.ConnectorMessage.register:type_name -> connector.RegisterRequest
	5,  // 1: connector.ConnectorMessage.flight_info:type_name -> connector.FlightInfoResponse
	7,  // 2: connector.ConnectorMessage.arrow_chunk:type_name -> connector.ArrowChunk
	8,  // 3: connector.ConnectorMessage.stream_status:type_name -> connector.StreamStatus
	10, // 4: connector.ConnectorMessage.heartbeat:type_name -> connector.HeartbeatResponse
	3,  // 5: connector.GatewayCommand.register_response:type_name -> connector.RegisterResponse
	4,  // 6: connector.GatewayCommand.get_flight_info:type_name -> connector.GetFlightInfoRequest
	6,  // 7: connector.GatewayCommand.do_get:type_name -> connector.DoGetRequest
	9,  // 8: connector.GatewayCommand.heartbeat:type_name -> connector.Heartbeat
	0,  // 9: connector.ConnectorService.Connect:input_type -> connector.ConnectorMessage
	1,  // 10: connector.ConnectorService.Connect:output_type -> connector.GatewayCommand
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_connector_proto_init() }
func file_proto_connector_proto_init() {
	if File_proto_connector_proto != nil {
		return
	}
	file_proto_connector_proto_msgTypes[0].OneofWrappers = []any{
		(*ConnectorMessage_Register)(nil),
		(*ConnectorMessage_FlightInfo)(nil),
		(*ConnectorMessage_ArrowChunk)(nil),
		(*ConnectorMessage_StreamStatus)(nil),
		(*ConnectorMessage_Heartbeat)(nil),
	}
	file_proto_connector_proto_msgTypes[1].OneofWrappers = []any{
		(*GatewayCommand_RegisterResponse)(nil),
		(*GatewayCommand_GetFlightInfo)(nil),
		(*GatewayCommand_DoGet)(nil),
		(*GatewayCommand_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_connector_proto_rawDesc), len(file_proto_connector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_connector_proto_goTypes,
		DependencyIndexes: file_proto_connector_proto_depIdxs,
		MessageInfos:      file_proto_connector_proto_msgTypes,
	}.Build()
	File_proto_connector_proto = out.File
	file_proto_connector_proto_goTypes = nil
	file_proto_connector_proto_depIdxs = nil
}
